--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#002b36"
foreground="#839496"
cursor="#839496"

-- Colors
color0="#073642"
color1="#dc322f"
color2="#859900"
color3="#b58900"
color4="#268bd2"
color5="#d33682"
color6="#2aa198"
color7="#eee8d5"
color8="#002b36"
color9="#cd4b16"
color10="#586e75"
color11="#657b83"
color12="#839496"
color13="#6c71c4"
color14="#93a1a1"
color15="#fdf6e3"
