# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#002b36'
foreground='#839496'
cursor='#839496'

# Colors
color0='#073642'
color1='#dc322f'
color2='#859900'
color3='#b58900'
color4='#268bd2'
color5='#d33682'
color6='#2aa198'
color7='#eee8d5'
color8='#002b36'
color9='#cd4b16'
color10='#586e75'
color11='#657b83'
color12='#839496'
color13='#6c71c4'
color14='#93a1a1'
color15='#fdf6e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
